### PR TITLE
Toggle dark mode

### PR DESCRIPTION
**Pull request by roth-dev**

### CODE REVIEW

**Comment by roth-dev** [comment]
Should be close: [https://github.com/outerbase/studio-desktop/issues/10](url)

**Comment by invisal** [comment]
We need to set the dark mode here as well:

https://github.com/outerbase/studio-desktop/blob/master/electron/main.ts#L77

```
  const queryString = new URLSearchParams({ name: conn.name, theme: "dark" | "light" }).toString();
```

I believe you cannot use localStorage to do it. You need to write it to file.

You can check https://github.com/outerbase/studio-desktop/blob/master/electron/file-helper.ts#L5 on how to deal with which path to write. Try to write to `setting.json`. 

Create setting class

```
const setting = new Setting();
setting.load();  // load the setting from file. If no file, make it
```

**Comment by roth-dev** [comment]
> We need to set the dark mode here as well:
> 
> https://github.com/outerbase/studio-desktop/blob/master/electron/main.ts#L77
> 
> ```
>   const queryString = new URLSearchParams({ name: conn.name, theme: "dark" | "light" }).toString();
> ```
> 
> I believe you cannot use localStorage to do it. You need to write it to file.
> 
> You can check https://github.com/outerbase/studio-desktop/blob/master/electron/file-helper.ts#L5 on how to deal with which path to write. Try to write to `setting.json`.
> 
> Create setting class
> 
> ```
> const setting = new Setting();
> setting.load();  // load the setting from file. If no file, make it
> setting.get("theme") // get theme value
> setting.set("theme", "dark"); // set dark mode and write to file
> ```
> 
> Then, you can use ipc to set it from renderer window.

Let me change it.

**Comment by roth-dev** [comment]
All updated according to suggestion.

**Comment by jccbbb** [comment]
How do you activate darkmode in the Windows desktop app?

**Pull request merged**
